# Generated by Django 3.0.4 on 2020-04-21 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=30)),
                ('Pincoad', models.IntegerField(max_length=10)),
                ('Price', models.FloatField(max_length=50)),
                ('Published_Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Plot_size', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Bedrooms', models.IntegerField(max_length=10)),
                ('bathrooms', models.IntegerField(max_length=10)),
                ('parking', models.IntegerField(max_length=10)),
                ('Enterance', models.IntegerField()),
                ('Aditional_Details', models.TextField()),
                ('Name_of_owener', models.CharField(max_length=30)),
                ('Main_image', models.ImageField(upload_to='image')),
                ('Optional_image1', models.ImageField(blank=True, upload_to='image')),
                ('Optional_image2', models.ImageField(blank=True, upload_to='image')),
                ('Optional_image3', models.ImageField(blank=True, upload_to='image')),
                ('Optional_image4', models.ImageField(blank=True, upload_to='image')),
                ('Optional_image5', models.ImageField(blank=True, upload_to='image')),
                ('Realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor')),
            ],
        ),
    ]
