# Generated by Django 3.0.4 on 2020-04-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200422_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Is_published',
            field=models.BooleanField(default=False),
        ),
    ]
