# Generated by Django 3.0.4 on 2020-04-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Realtor',
            new_name='Realtor_Name',
        ),
    ]
