# Generated by Django 3.0.4 on 2020-04-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200430_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Pincoad',
            field=models.CharField(max_length=100),
        ),
    ]
