# Generated by Django 3.0.4 on 2020-04-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200430_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Cities',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
