# Generated by Django 3.0.4 on 2020-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_remove_realtor_proporties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='Contect',
            field=models.CharField(max_length=20),
        ),
    ]
